---
theme-url: https://cdn.jsdelivr.net/gh/trossi/slidefactory@c0b52a3ac328738abf58b19bcd77df323032f06f/theme/csc-2023/csc.css
css: https://fonts.googleapis.com/css?family=Noto+Sans:,i,b,bi|Inconsolata:,b&subset=greek,latin-ext
revealjs-url: https://cdn.jsdelivr.net/npm/reveal.js@4.4.0
---
